# Generated by Django 2.2.9 on 2021-11-05 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('cidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('criador', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('cidade', models.CharField(max_length=100)),
                ('Projeto', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProjeto', models.CharField(max_length=50, verbose_name='Nome do Projeto')),
                ('dataInicio', models.DateTimeField(auto_now_add=True)),
                ('atualiza', models.DateTimeField(auto_now=True)),
                ('dataLimite', models.DateField(blank=True, null=True, verbose_name='Data Limite')),
                ('descreva', models.TextField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aluno')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Empresa')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='Projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Empresa'),
        ),
    ]
