# Generated by Django 2.2.24 on 2021-11-13 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211105_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='criador',
            new_name='empresaNome',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='nome',
            new_name='representanteNome',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='Projeto_id',
        ),
    ]
