# Generated by Django 2.2.24 on 2021-11-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211105_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='criador',
            new_name='documento',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='projeto',
            new_name='empresa',
        ),
    ]
