# Generated by Django 2.2.24 on 2021-11-13 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211112_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='empresaNome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='representanteNome',
            new_name='representante',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='nomeProjeto',
            new_name='nome',
        ),
    ]
