# Generated by Django 2.2.24 on 2021-11-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211112_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='aluno',
            new_name='responsavel',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='nome',
            new_name='titulo',
        ),
    ]
