# Generated by Django 2.2.24 on 2021-11-22 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Aluno')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('telefone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Empresa')),
                ('representante', models.CharField(max_length=50, verbose_name='Nome do Representante')),
                ('sobrenomerepre', models.CharField(max_length=50, verbose_name='Sobrenome do Representante')),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Nome do Projeto')),
                ('dataInicio', models.DateTimeField(auto_now_add=True, verbose_name='Data Inicial')),
                ('atualiza', models.DateTimeField(auto_now=True)),
                ('dataLimite', models.DateField(blank=True, null=True, verbose_name='Data Limite')),
                ('descreva', models.TextField(blank=True, null=True, verbose_name='Descreva o Projeto')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aluno')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Empresa')),
            ],
        ),
    ]
