# Generated by Django 2.2.24 on 2021-11-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='dataLimite',
            field=models.DateField(verbose_name='Data Limite'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descreva',
            field=models.TextField(verbose_name='Descreva o Projeto'),
        ),
    ]
