# Generated by Django 2.2.24 on 2021-11-23 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20211123_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='empresa',
        ),
        migrations.AddField(
            model_name='projeto',
            name='usuarioEmpresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
