# Generated by Django 2.2.24 on 2021-11-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211123_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='usuarioEmpresa',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='usuarioEmpresa',
            new_name='empresa',
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
