# Generated by Django 2.2.24 on 2021-11-25 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211125_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Empresa')),
                ('representante', models.CharField(max_length=50, verbose_name='Nome do Representante')),
                ('sobrenomerepre', models.CharField(max_length=50, verbose_name='Sobrenome do Representante')),
                ('telefone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('P', 'Projeto postado'), ('F', 'Em andamento'), ('E', 'Realizados')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projeto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projeto', to='core.Empresa'),
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Aluno')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('telefone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('Projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisita', to='core.Projeto')),
            ],
        ),
    ]
