# Generated by Django 2.2.24 on 2021-11-28 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211128_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='core.Empresa'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('P', 'Projeto postado'), ('F', 'Em andamento'), ('E', 'Realizados')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Titulo do Projeto'),
        ),
    ]
