# Generated by Django 2.2.24 on 2021-11-28 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_projeto_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='username',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Empresa', to='core.Empresa'),
            preserve_default=False,
        ),
    ]
