# Generated by Django 2.2.24 on 2021-11-29 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20211128_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='username',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Empresa', to='core.Empresa'),
            preserve_default=False,
        ),
    ]
