# Generated by Django 3.2.9 on 2021-11-29 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20211128_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Empresa', to='core.empresa'),
        ),
    ]
