# Generated by Django 2.2.24 on 2021-11-25 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='alunopk',
            new_name='aluno',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='empresapk',
        ),
        migrations.AddField(
            model_name='empresa',
            name='empresa',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
