# Generated by Django 2.2.24 on 2021-11-25 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20211125_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='empresa',
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
