# Generated by Django 2.2.24 on 2021-11-25 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0003_auto_20211125_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(max_length=18, null=True, verbose_name='CNPJ')),
                ('representante', models.CharField(max_length=20, null=True, verbose_name='Nome do Representante')),
                ('sobrenomerepre', models.CharField(max_length=100, null=True, verbose_name='Sobrenome do Representante')),
                ('telefone', models.CharField(max_length=15, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=100, null=True, unique=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, null=True, verbose_name='Nome do Aluno')),
                ('sobrenome', models.CharField(max_length=100, null=True, verbose_name='Sobrenome')),
                ('cpf', models.CharField(max_length=14, null=True, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=15, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=100, null=True, unique=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
