# Generated by Django 2.2.24 on 2021-11-25 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_aluno_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='aluno',
            new_name='usuarios_aluno',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='empresa',
            new_name='usuarios_empresa',
        ),
    ]
