# Generated by Django 2.2.24 on 2021-11-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20211125_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='usuarios_aluno',
            new_name='username',
        ),
    ]
