# Generated by Django 2.2.24 on 2021-11-28 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_empresa_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='usuarios_empresa',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='username',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
